url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "streamkeeper" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

exclude: ["Gemfile*", "Rakefile", "package*.json", "*.config.js", "media_parser.rb"]
